### PR TITLE
Add checkbox to show full percentage scale from 0 to 100

### PR DESCRIPTION
**Pull request by leijurv**
Screenshots showing the effect of this checkbox, for example on Tamzin's RFA:

image
image

### CODE REVIEW

**Comment by enterprisey** [comment]
would it be possible to make the red less harsh when the full thing is shown?

**Comment by leijurv** [comment]
I'm not sure - I see the colors defined here https://github.com/enterprisey/vote-history/blob/master/js/support-percentage-color-codes.js as hex codes, I guess there could be an alternate set of colors for "full scale mode" where they're...... desaturated I guess?

But I didn't do anything to the colors that's just how they are.

**Comment by leijurv** [comment]
I see they're directly from https://en.wikipedia.org/w/index.php?title=Template:Bureaucrat_candidate/expr&action=edit it seems?

**Comment by leijurv** [comment]
I think it might be surprising / unexpected though, if you clicked the "show full scale" checkbox and it toned down the colors in the whole thing. So I guess maybe it would only want to show muted colors for the new section that isn't shown previously? But that would have a jump in saturation that would be confusing, might look like there's some threshold that the final percentage is exactly touching.

**Comment by enterprisey** [comment]
maybe we could move the colors to a bar on the side, or color the line? or I guess since this is opt-in behavior we can just do nothing and merge as-is

**Comment by leijurv** [comment]
Since this is the same coloring as the default scale I'd say it's probably fine? Especially since it's opt-in?

**Comment by enterprisey** [comment]
sure

**Comment by enterprisey** [comment]
thanks for the patch!

**Pull request merged**
